# Generated by Django 4.2.4 on 2024-01-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=15)),
                ('Is_Admin', models.BooleanField(default=False)),
                ('Is_Citizen', models.BooleanField(default=False)),
                ('Is_Committee', models.BooleanField(default=False)),
                ('Is_Security', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BirthDate', models.DateField(auto_created=True, default='1980-12-11')),
                ('TotalMembers', models.CharField(default='', max_length=50)),
                ('BlockNo', models.CharField(default='', max_length=10)),
                ('HouseNo', models.CharField(default='', max_length=10)),
                ('Resident_Type', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], default='', max_length=20)),
                ('FirstName', models.CharField(default='', max_length=20)),
                ('LastName', models.CharField(default='', max_length=20)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=20)),
                ('Email', models.EmailField(default='', max_length=30)),
                ('Profession', models.CharField(default='', max_length=50)),
                ('Contact', models.CharField(default='', max_length=10)),
                ('Contac2t', models.CharField(default='', max_length=10)),
                ('Address', models.CharField(default='', max_length=40)),
                ('singup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.singup')),
            ],
        ),
    ]
