# Generated by Django 4.2.4 on 2024-01-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0002_citizen_registration_adharnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BirthDate', models.DateField(auto_created=True, default='1980-12-11')),
                ('Email', models.EmailField(default='', max_length=30)),
                ('Contact', models.CharField(default='', max_length=10)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=20)),
                ('AdharNumber', models.CharField(default='', max_length=20)),
                ('singup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.singup')),
            ],
        ),
    ]
