# Generated by Django 4.2.4 on 2024-01-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0006_alter_citizen_registration_houseno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singup',
            name='Username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
