# Generated by Django 4.2.4 on 2024-01-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0007_alter_singup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen_registration',
            name='singup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.singup', unique=True),
        ),
    ]
