# Generated by Django 4.2.4 on 2024-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0011_add_block_add_house_add_society_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_society',
            name='Address',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='add_society',
            name='Society_Name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
