# Generated by Django 4.2.4 on 2024-01-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0013_delete_add_block_delete_add_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry_Date', models.DateField(auto_created=True, default='1990/23/12')),
                ('House_No', models.IntegerField(default=100)),
                ('Block_No', models.IntegerField(default=50)),
                ('House_Type', models.CharField(choices=[('2bhk', '2BHK'), ('3bhk', '3BHK'), ('1bhk', '1BHK')], max_length=50)),
                ('Detail', models.TextField(default='', max_length=50)),
                ('Image', models.ImageField(upload_to=None)),
                ('Society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.add_society')),
            ],
        ),
    ]
