# Generated by Django 4.2.4 on 2024-01-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0014_add_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='Detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('1bhk', '1BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
    ]
