# Generated by Django 4.2.4 on 2024-01-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0015_alter_add_house_detail_alter_add_house_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('3bhk', '3BHK'), ('1bhk', '1BHK'), ('2bhk', '2BHK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='add_society',
            name='Address',
            field=models.TextField(max_length=50),
        ),
    ]
