# Generated by Django 4.2.4 on 2024-01-14 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0016_alter_add_house_house_type_alter_add_society_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('3bhk', '3BHK'), ('1bhk', '1BHK')], max_length=50),
        ),
        migrations.CreateModel(
            name='Add_Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_No', models.IntegerField(default='')),
                ('No_Of_Floors', models.IntegerField(default='')),
                ('Society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.add_society')),
            ],
        ),
    ]
