# Generated by Django 4.2.4 on 2024-01-14 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0016_alter_add_house_house_type_alter_add_society_address'),
    ]

    operations = [
       
        
    ]
