# Generated by Django 4.2.4 on 2024-01-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0017_alter_add_house_house_type_add_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='Block_No',
            field=models.CharField(default="",max_length=50),
        ),
        
    ]
