# Generated by Django 4.2.4 on 2024-01-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0020_remove_add_house_block_no_add_house_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_house',
            name='Block_No',
        ),
        migrations.AddField(
            model_name='add_house',
            name='Block',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('3bhk', '3BHK'), ('1bhk', '1BHK'), ('2bhk', '2BHK')], max_length=50),
        ),
    ]
