# Generated by Django 4.2.4 on 2024-01-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0021_remove_add_house_block_no_add_house_block_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_house',
            old_name='Block',
            new_name='Block_No',
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('1bhk', '1BHK'), ('3bhk', '3BHK'), ('2bhk', '2BHK')], max_length=50),
        ),
    ]
