# Generated by Django 4.2.4 on 2024-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0021_remove_add_block_no_of_flats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='Block_No',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='Add_Block',
        ),
    ]
