# Generated by Django 4.2.4 on 2024-01-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0022_rename_block_add_house_block_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_New_Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_No', models.CharField(default='', max_length=50)),
                ('NO_Of_Floors', models.IntegerField(default='')),
                ('No_Of_Flats', models.IntegerField(default='')),
                ('Society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.add_society')),
            ],
        ),
    ]
