# Generated by Django 4.2.4 on 2024-01-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0022_alter_add_house_block_no_delete_add_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_house',
            name='Block_No',
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('3bhk', '3BHK'), ('2bhk', '2BHK'), ('1bhk', '1BHK')], max_length=50),
        ),
    ]
