# Generated by Django 4.2.4 on 2024-01-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0023_remove_add_house_block_no_alter_add_house_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_house',
            name='Block_No',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('3bhk', '3BHK'), ('1bhk', '1BHK')], max_length=50),
        ),
    ]
