# Generated by Django 4.2.4 on 2024-01-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0025_alter_add_house_block_no_alter_add_house_house_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_house',
            old_name='Society',
            new_name='Society_Name',
        ),
        migrations.RenameField(
            model_name='add_new_block',
            old_name='Society',
            new_name='Society_Name',
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('3bhk', '3BHK'), ('1bhk', '1BHK')], max_length=50),
        ),
    ]
