# Generated by Django 4.2.4 on 2024-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0027_alter_add_house_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='Entry_Date',
            field=models.DateField(auto_created=True, default='1990/23/12'),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('1bhk', '1BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
    ]
