# Generated by Django 4.2.4 on 2024-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0033_arrange_meeting_alter_add_house_house_type'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='add_house',
            name='Entry_Date',
            field=models.DateField(auto_created=True, default='2018-12-12'),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('1bhk', '1BHK'), ('2bhk', '2BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='add_society',
            name='Entry_Date',
            field=models.DateField(auto_created=True, default='2018-12-12'),
        ),
        migrations.AlterField(
            model_name='citizen_registration',
            name='BirthDate',
            field=models.DateField(auto_created=True, default='2018-12-12'),
        ),
        migrations.AlterField(
            model_name='committee_registration',
            name='BirthDate',
            field=models.DateField(auto_created=True, default='2018-12-12'),
        ),
        migrations.AlterField(
            model_name='security_registration',
            name='BirthDate',
            field=models.DateField(auto_created=True, default='2018-12-12'),
        ),
    ]
