# Generated by Django 4.2.4 on 2024-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0042_alter_add_house_house_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen_registration',
            name='Profession',
        ),
        migrations.RemoveField(
            model_name='singup',
            name='Is_Admin',
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('1bhk', '1BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
    ]
