# Generated by Django 4.2.4 on 2024-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0043_remove_citizen_registration_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singup',
            name='Is_Admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('1bhk', '1BHK'), ('3bhk', '3BHK'), ('2bhk', '2BHK')], max_length=50),
        ),
    ]
