# Generated by Django 4.2.4 on 2024-01-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0045_alter_add_house_house_type_sell_house_rent_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('1bhk', '1BHK'), ('3bhk', '3BHK'), ('2bhk', '2BHK')], max_length=50),
        ),
        migrations.CreateModel(
            name='Personal_Event_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry_Date', models.DateField(auto_created=True, default='2018-12-12')),
                ('Event_Name', models.CharField(default='', max_length=50)),
                ('No_Of_Guest', models.IntegerField(default='')),
                ('Citizen_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.singup')),
                ('House_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.add_house')),
                ('Society_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.add_society')),
            ],
        ),
    ]
