# Generated by Django 4.2.4 on 2024-01-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0046_alter_add_house_house_type_personal_event_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='House_No',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('3bhk', '3BHK'), ('2bhk', '2BHK'), ('1bhk', '1BHK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arrange_meeting',
            name='Meet_Agenda',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='personal_event_booking',
            name='No_Of_Guest',
            field=models.IntegerField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.TextField(default='')),
                ('Citizen_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.singup')),
            ],
        ),
    ]
