# Generated by Django 4.2.4 on 2024-01-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0047_alter_add_house_house_no_alter_add_house_house_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='House_No',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('1bhk', '1BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personal_event_booking',
            name='No_Of_Guest',
            field=models.IntegerField(default=''),
        ),
    ]
