# Generated by Django 4.2.4 on 2024-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0050_alter_add_house_house_type_alter_complain_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complain_Name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('1bhk', '1BHK'), ('3bhk', '3BHK'), ('2bhk', '2BHK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
