# Generated by Django 4.2.4 on 2024-01-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0051_complain_type_alter_add_house_house_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='Complain_Type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('1bhk', '1BHK'), ('2bhk', '2BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
    ]
