# Generated by Django 4.2.4 on 2024-01-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0052_complain_complain_type_alter_add_house_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('3bhk', '3BHK'), ('1bhk', '1BHK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='Complain_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.complain_type'),
        ),
    ]
