# Generated by Django 4.2.4 on 2024-01-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0053_alter_add_house_house_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateField(auto_created=True, default='2018-12-12')),
                ('Guest_Name', models.CharField(default='', max_length=50)),
                ('Reason_for_Comming', models.TextField(default='')),
                ('Contact', models.CharField(default='', max_length=50)),
                ('Citizen_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.citizen_registration')),
                ('Security_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.singup')),
            ],
        ),
    ]
