# Generated by Django 4.2.4 on 2024-01-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0054_guest_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateField(auto_created=True, default='2018-12-12')),
                ('Notice', models.CharField(default='', max_length=50)),
                ('Subject', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='complain',
            old_name='Complain_Type',
            new_name='Complain',
        ),
    ]
