# Generated by Django 4.2.4 on 2024-01-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0055_notice_rename_complain_type_complain_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raise_Funt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateField(auto_created=True, default='2018-12-12')),
                ('Fund_Type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Society_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateField(auto_created=True, default='2018-12-12')),
                ('Event_Name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('3bhk', '3BHK'), ('1bhk', '1BHK'), ('2bhk', '2BHK')], max_length=50),
        ),
    ]
