# Generated by Django 4.2.4 on 2024-01-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0056_raise_funt_society_event_alter_add_house_house_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fund_Type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('3bhk', '3BHK'), ('1bhk', '1BHK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='raise_funt',
            name='Fund_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.fund_type'),
        ),
    ]
