# Generated by Django 4.2.4 on 2024-01-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0057_fund_type_alter_add_house_house_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notice_Name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='fund_type',
            old_name='Fund_Type',
            new_name='Fund_Name',
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('1bhk', '1BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
    ]
