# Generated by Django 4.2.4 on 2024-01-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0061_rename_event_name_society_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('1bhk', '1BHK'), ('2bhk', '2BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='society_event',
            name='Event_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_App.event_type'),
        ),
    ]
