# Generated by Django 4.2.4 on 2024-01-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0063_rename_raise_funt_raise_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen_registration',
            name='Profession',
            field=models.CharField(default='', max_length=50),
        ),
    ]
