# Generated by Django 4.2.4 on 2024-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0064_citizen_registration_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singup',
            name='Email',
        ),
        migrations.AddField(
            model_name='citizen_registration',
            name='Email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='committee_registration',
            name='Email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='security_registration',
            name='Email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('1bhk', '1BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
    ]
