# Generated by Django 4.2.4 on 2024-01-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0067_rename_nohouse_add_society_no_of_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('3bhk', '3BHK'), ('1bhk', '1BHK'), ('2bhk', '2BHK')], max_length=50),
        ),
    ]
