# Generated by Django 4.2.4 on 2024-01-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0070_alter_add_house_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('1bhk', '1BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='Image',
            field=models.FileField(default='avatar.png', upload_to='house_images/'),
        ),
        migrations.AlterField(
            model_name='add_society',
            name='Society_Image',
            field=models.FileField(default='avatar.png', upload_to='society_images/'),
        ),
    ]
