# Generated by Django 4.2.4 on 2024-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0074_alter_add_house_house_no_alter_add_house_house_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='Relpay',
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('3bhk', '3BHK'), ('2bhk', '2BHK'), ('1bhk', '1BHK')], max_length=50),
        ),
    ]
