# Generated by Django 4.2.4 on 2024-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0075_remove_complain_relpay_alter_add_house_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_entry',
            name='Citizen_Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
