# Generated by Django 4.2.4 on 2024-02-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0079_alter_add_house_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='security_registration',
            name='society',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Society_App.add_society'),
            preserve_default=False,
        ),
    ]
