# Generated by Django 4.2.4 on 2024-02-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0080_security_registration_society'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security_registration',
            old_name='society',
            new_name='Society_Name',
        ),
    ]
