# Generated by Django 4.2.4 on 2024-02-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0084_alter_add_house_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='security_registration',
            name='Society_Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Society_App.add_society'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('3bhk', '3BHK'), ('1bhk', '1BHK')], max_length=50),
        ),
    ]
