# Generated by Django 4.2.4 on 2024-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0086_remove_security_registration_society_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='security_registration',
            name='society_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('3bhk', '3BHK'), ('1bhk', '1BHK')], max_length=50),
        ),
    ]
