# Generated by Django 4.2.4 on 2024-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0087_security_registration_society_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest_entry',
            name='Society_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('1bhk', '1BHK'), ('3bhk', '3BHK'), ('2bhk', '2BHK')], max_length=50),
        ),
    ]
