# Generated by Django 4.2.4 on 2024-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0088_guest_entry_society_name_alter_add_house_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen_registration',
            name='Citizen_Image',
            field=models.FileField(default='Avatar.png', upload_to='Citizen_Images/'),
        ),
        migrations.AddField(
            model_name='committee_registration',
            name='Committee_Image',
            field=models.FileField(default='Avatar.png', upload_to='Committee_Person_Images/'),
        ),
        migrations.AddField(
            model_name='security_registration',
            name='Security_Image',
            field=models.FileField(default='Avatar.png', upload_to='Security_Person_Images/'),
        ),
        migrations.AlterField(
            model_name='add_house',
            name='House_Type',
            field=models.CharField(choices=[('2bhk', '2BHK'), ('1bhk', '1BHK'), ('3bhk', '3BHK')], max_length=50),
        ),
    ]
